### PR TITLE
Upgrades to align to Spring Boot 3.3.1 and json-io 4.26.0

### PR DESCRIPTION
**Pull request by pacphi**

### CODE REVIEW

**Comment by pacphi** [comment]
I am using the `3.1.6-SNAPSHOT` of `java-cf-env-boot` on this `cf-butler` [branch](https://github.com/cf-toolsuite/cf-butler/tree/cfenv-update). While the Github workflow [fails](https://github.com/cf-toolsuite/cf-butler/actions/runs/10015736394/job/27687616590) (b/c the aforementioned snapshot artifact must be built and locally cached in `$HOME/.m2/repository` or published to a publicly resolvable snapshot repo), I followed these steps to build, integrate, and deploy an updated `cf-butler` artifact to Dhaka (an internally hosted Tanzu Platform for Cloud Foundry environment):

1. Fork `java-cfenv` repo with `gh repo fork pivotal-cf/java-cfenv`
2. Make updates. Commit them on fork's `main` branch. File a PR via Github.  See the [files changed](https://github.com/pivotal-cf/java-cfenv/pull/266/files).

Meanwhile we need proof these changes function as-desired, so

3. Clone `cf-butler` repo with `gh clone repo cf-toolsuite/cf-butler`. Change directories with `cd cf-butler`.
4. Use Maven to build executable JAR with `mvn clean package -Pexpose-runtime-metadata`. (Requires JDK 21 or better).
5. Create a secrets configuration file named `secrets.dhaka.json` in a directory named `config`

This is a sample of the contents

```json
{
    "CF_TOKEN-PROVIDER": "sso",
    "CF_API-HOST": "api.sys.dhaka.cf-app.com",
    "CF_REFRESH-TOKEN": "[replace_me]",
    "CF_ACCOUNT-REGEX": "^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$",
    "CRON_COLLECTION": "0 0 0 * * *",
    "CF_POLICIES_GIT_URI": "https://github.com/pacphi/cf-butler-config.git",
    "CF_POLICIES_GIT_FILE-PATHS": [
        "change-stack-applications-policy-sample-AP.json",
        "emergency-notice-sample-HP.json",
        "endpoint-policy-sample-EP.json",
        "hygiene-policy-sample-HP.json",
        "legacy-policy-sample-LP.json",
        "query-policy-h2-sample-QP.json",
        "delete-applications-policy-sample-AP.json",
        "delete-service-instances-policy-sample-SIP.json",
        "scale-applications-policy-sample-AP.json",
        "stop-applications-policy-sample-AP.json"
    ],
    "EXPOSED_ACTUATOR_ENDPOINTS": "info,jars,health,heapdump,pom,threaddump,metrics,scheduledtasks,loggers,mappings,prometheus,sbom",
    "JAVA_ARTIFACTS_FETCH_MODE": "list-jars-in-droplet"
}
```
6. Set API endpoint with `cf api api.sys.dhaka.cf-app.com`
7. Authenticate with `cf login --sso`
8. Create a new organization and space as the home for your application instance of `cf-butler` with

```sh
cf create-org cftoolsuite
cf create-space observability -o cftoolsuite
cf target -o cftoolsuite -s observability
```

9. Obtain a refresh token by executing `cat $HOME/.cf/config.json | jq .RefreshToken`. Replace the `[replace_me]` value in thew secrets file configuration above with the resulting refresh token value.

10. Deploy `cf-butler` utilizing a convenience [script](https://github.com/cf-toolsuite/cf-butler/blob/cfenv-update/scripts/deploy.alt.sh).  Execute `./scripts/deploy.alt.sh -c config/secrets.dhaka.json`. (If the app fails due to a route collision, just follow up with `cf push --random-route`).

11. Inspect the log output with `cf logs cf-butler --recent`. We're looking for some output like

```sh
2024-07-19T16:28:55.80-0700 [APP/PROC/WEB/0] OUT 23:28:55.808 [main] INFO  i.p.c.s.b.CfEnvironmentPostProcessor - Setting null properties from bound service [cf-butler-secrets] using org.cftoolsuite.cfapp.config.ButlerCfEnvProcessor
   2024-07-19T16:28:55.80-0700 [APP/PROC/WEB/0] OUT 23:28:55.809 [main] INFO  i.p.c.s.b.CfEnvironmentPostProcessor - Setting null properties from bound service [cf-butler-secrets] using io.pivotal.cfenv.spring.boot.CredHubCfEnvProcessor
```

12. To prove that the required application config was loaded correctly into the Credhub instance and honored, execute:

```sh
http https://cf-butler-turbulent-whale-uv.apps.dhaka.cf-app.com/snapshot/detail/ai/spring
```
> Change the route above as needed.

And you should see something like 

```sh
HTTP/1.1 200 OK
Content-Type: application/json
Date: Sat, 20 Jul 2024 00:39:17 GMT
Transfer-Encoding: chunked
X-Vcap-Request-Id: 6c05118d-7cec-49eb-5347-c40b0c8e737f

[
    {
        "appId": "b3c6ce97-0b84-4873-add7-b761059a5e1d",
        "appName": "cf-butler",
        "dropletId": "63527a99-e936-4c6f-b8b0-16ea4ac6fcad",
        "organization": "cf-toolsuite",
        "space": "observability",
        "springDependencies": "org.springframework.data:3.3.1, org.springframework.boot:3.3.1, org.springframework:6.1.10"
    }
]
```

**Comment by pacphi** [comment]
It should be noted that `cf-butler` uses the `pivotal-cf/spring-cloud-dependencies` [BOM](https://github.com/pivotal-cf/spring-cloud-services-starters?tab=readme-ov-file#maven-bom) in the `dependencyManagement` section of its POM.  This has the unfortunate effect of pinning the version of `java-cfenv` to `3.1.5`, see https://repo1.maven.org/maven2/io/pivotal/spring/cloud/spring-cloud-services-dependencies/4.1.3/spring-cloud-services-dependencies-4.1.3.pom.  

So in the `cf-butler` POM I had to explicitly specify both `java-cfenv` and `java-cfenv-boot` dependency versions.

Outside the scope of this PR, but when you eventually release updated versions of `java-cfenv*` artifacts, you should update the version specified in `pivotal-cf/spring-cloud-dependencies`, and release updated POM version too.

**Comment by anthonydahanne** [comment]
thanks a lot @pacphi for all those details! I'll bookmark this PR for future reference!

when you said:
> Outside the scope of this PR, but when you eventually release updated versions of java-cfenv* artifacts, you should update the version specified in pivotal-cf/spring-cloud-dependencies, and release updated POM version too.

Can you please share the repo url, I could not find it?!

Thank you!

**Comment by pacphi** [comment]
The repo that has a dependency on `java-cfenv` is this one: https://github.com/pivotal-cf/spring-cloud-services-starters/tree/main.  Specifically, see: https://github.com/pivotal-cf/spring-cloud-services-starters/blob/main/build.gradle#L229.

**Pull request merged**
