### PR TITLE
Is enabled

### LINKED ISSUE #28: Add isEnabled method to CfEnvProcessor to allow for each implementation to be turned off via an environment variable.

### PR DESCRIPTION
**Pull request by dturanski**
Fixes #28 
Depends on (includes) #35

### CODE REVIEW

**Comment by dturanski** [comment]
DO NOT merge yet. Does not handle multiple services of same type.

**Comment by maximusfloydus** [comment]
@dturanski Are you going to update this for the latest code?  I am looking for a solution similar to this.  I would like to use the library for some bindings: SCS config, SCS registry, SCS SSO.  Then I don't want to use it for RabbitMQ because I have multiple to support in a single JVM.

**Comment by dturanski** [comment]
@dyroberts - What's the status on this? I don't recall the details.

**Comment by dyroberts** [comment]
I've rebased this onto master and created a new PR.
https://github.com/pivotal-cf/java-cfenv/pull/88

**Pull request closed without merging**
