### PR TITLE
Add Cloud profile

### PR DESCRIPTION
**Pull request by anthonydahanne**

### CODE REVIEW

**Comment by anthonydahanne** [comment]
Ready to go!
I tested it with spring-music no cfenv and JBP

```
   2023-09-13T17:01:18.02-0400 [APP/PROC/WEB/0] OUT :: Spring Boot ::                (v3.1.3)
   2023-09-13T17:01:18.17-0400 [APP/PROC/WEB/0] OUT 2023-09-13T21:01:18.170Z  INFO 7 --- [           main] o.c.samples.music.Application            : Starting Application v1.0 using Java 17.0.8 with PID 7 (/home/vcap/app/BOOT-INF/classes started by vcap in /home/vcap/app)
   2023-09-13T17:01:18.17-0400 [APP/PROC/WEB/0] OUT 2023-09-13T21:01:18.179Z  INFO 7 --- [           main] o.c.samples.music.Application            : The following 2 profiles are active: "cloud", "http2"
   2023-09-13T17:01:18.33-0400 [APP/PROC/WEB/0] OUT 2023-09-13T21:01:18.335Z  INFO 7 --- [           main] i.p.c.p.CloudProfileApplicationListener  : 'cloud' profile activated
   2023-09-13T17:01:18.33-0400 [APP/PROC/WEB/0] OUT 2023-09-13T21:01:18.337Z  INFO 7 --- [           main] s.b.CfDataSourceEnvironmentPostProcessor : Setting spring.datasource properties from bound service [mysql-service]

```

**Comment by massiinthesea** [comment]
Hello, 

With this new version, the "cloud" profile is systematically added.

In older versions, it was removed with this option in the manifest. 
JBP_CONFIG_SPRING_AUTO_RECONFIGURATION: '{ enabled: false }'

Now, this function doesn't seem to remove the profile, and this is causing me problems. Would you have a solution for removing it in this new buildpack version? 

Thank you very much.

**Comment by craig41** [comment]
hello,

this appears to be causing applications that utilize this package to launch under the cloud profile always. was this the intended behavior?

**Comment by anthonydahanne** [comment]
hello @craig41 , @massiinthesea  - yes the idea is to fill the gap with Spring Auto Reconfiguration, the former library, that injected this profile automatically.

> In older versions, it was removed with this option in the manifest.
JBP_CONFIG_SPRING_AUTO_RECONFIGURATION: '{ enabled: false }'

That option disables the injection of the Spring Auto Reconfiguration library.

If you don't want java-cf-env to be injected by the Java Buildpack in CF, you can disable this behavior - the same you could do with SAR:

```
JBP_CONFIG_JAVA_CF_ENV: '{enabled: false}'
```

Finally, if you still want to have java-cf-env in your classpath, but not the cloud profile, you can add this [dependency](https://central.sonatype.com/artifact/io.pivotal.cfenv/java-cfenv-boot) to your pom, it will not get the cloud profile setter (which only exists in `java-cf-env-all`)

**Pull request merged**
